# -*- coding: utf-8 -*-
"""Steel Scrap Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18JjnwLQxhpUSswVtubw1KfaSLOU8cXv0
"""

# Pip install method (recommended)

!pip install ultralytics==8.0.196

from IPython import display


import ultralytics

from ultralytics import YOLO

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="Z0FUQ3a4D37YxWJjaFk1")
project = rf.workspace("image-annotation-rcdqd").project("steel-scrap-detection")
version = project.version(2)
dataset = version.download("yolov8")

!yolo task=detect mode=train model=yolov8s.pt data=/content/Steel-Scrap-detection-2/data.yaml epochs=75 imgsz=640 batch=16

!ls /content/runs/detect/train

!yolo task=detect mode=val model=/content/runs/detect/train/weights/best.pt data=/content/Steel-Scrap-detection-2/data.yaml

!yolo task=detect mode=predict model=/content/runs/detect/train/weights/best.pt conf=0.25 source=/content/Steel-Scrap-detection-2/test/images save=True















